---
title: "Old Availability Methods"
author: "Kelly Kapsar"
date: "3/11/2022"
output: html_document
---


```{r load libraries}

library(tidyr)
library(dplyr)
library(sf)
library(raster)
library(ggplot2)
library(scales)
library(ggmap)
library(amt) 

```

```{r read in data}

# Set seed
set.seed(1015)

# Projection information for WGS84/UTM Zone 5N (EPSG:32605)
prj <- 32605

# Create study area polygon
coords <- data.frame(lat=c(56, 62, 62, 56, 56), lon=c(-155, -155, -143, -143, -155), id="study")
study <- coords %>% 
         st_as_sf(coords = c("lon", "lat"), crs=4326) %>% 
         group_by(id) %>% 
         summarize(geometry = st_combine(geometry)) %>%  
         st_cast("POLYGON") %>% 
         st_transform(prj)

# Read in clean, non-land ssl used locations
ssl <- readRDS("../Data_Processed/Telemetry/watersealis.rds")
ssl$used <- factor(1)

# Create an ID column that identifies each unique individual/year/week combination
ssl$weeklyhr_id <- factor(paste0(ssl$deploy_id, ssl$year, ssl$weekofyear))

# st_write(ssl, "../Data_Processed/Telemetry/USedLocs_Clean.shp")

# Read in covariates 
landmask <- raster("../Data_Processed/Landmask_GEBCO.tif")
dist_500m <- raster("../Data_Processed/Dist500m.tif") %>% raster::mask(landmask, maskvalue=1)
depth <- raster("../Data_Processed/Bathymetry.tif") %>% raster::mask(landmask, maskvalue=1)
dist_land <- raster("../Data_Processed/DistLand.tif") %>% raster::mask(landmask, maskvalue=1)
slope <- raster("../Data_Processed/slope.tif") %>% raster::mask(landmask, maskvalue=1)

ship <- readRDS("../Data_Processed/AIS_AllOther.rds") 
fish <- readRDS("../Data_Processed/AIS_Fishing.rds")
eke1 <- readRDS("../Data_Processed/eke_weekly_20181101-20200531.rds")
eke2 <- readRDS("../Data_Processed/eke_weekly_20200601-20200731.rds")
ssh1 <- readRDS("../Data_Processed/ssh_weekly_20181101-20200531.rds")
ssh2 <- readRDS("../Data_Processed/ssh_weekly_20200601-20200731.rds")
load("../Data_Processed/sst_weekly.rda")
load("../Data_Processed/wind_weekly.rda")

# Create a list of all covariate files  and check resolution 
raslist <- list(depth, dist_land, dist_500m, slope, ship, fish, sst, eke1, eke2, ssh1, ssh2, wind)
rasres <- lapply(raslist, function(x) res(x)/1000)

# Create a vector of covar names 
covar_names <- c("bathymetry", "dist_land", "dist_500m", "slope", "ship", "fish", "sst", "eke", "ssh", "wind", "prox_fish_km", "prox_ship_km")

# Function to identify random points within a set of polygons 
# This also extracts raster values for static variables in the covar stack 
# Accounts for points on land 

custom_extract_avail <- function(poly, covarstack, npts = 5){
  maskstack <- raster::mask(covarstack, poly)
  df <-  as.data.frame(sampleRandom(x=maskstack, size = npts, na.rm = TRUE, ext = as(poly, "Spatial"), xy = TRUE))
  df$used <- factor(0)
  df$date <- poly$date
  df$deploy_id <- poly$deploy_id
  df$choice_id <- poly$choice_id
  df$year <- poly$year
  df$month <- poly$month
  df$weekofyear <- poly$weekofyear
  return(df)
}

# Extract dynamic covariate data at used locations 
### Modified from FROM AMT PACKAGE
# https://github.com/jmsigner/amt/blob/master/R/extract_covariates.R
# Also helpful: https://cran.r-project.org/web/packages/amt/vignettes/p3_rsf.html
# I modified it so that it works with weekly timescale data 
# DOES NOT work with holes in the data set any more 

extract_covar_var_time_custom <- function(
  xy, t, covariates) {

  t_covar <- raster::getZ(covariates)
  t_obs <- format(as.POSIXct(t), "%G-W%V") # Convert timestamp to week
  # Same week of year as lubridate::isoweek(ssl_dates$date)
  wr <- sapply(t_obs, function(x) which(x == t_covar)) # Identify which slice to select
  ev <- raster::extract(covariates, xy) # Extract covariate values for all time slices at all used locations 
  cov_val <- ev[cbind(seq_along(wr), wr)] # select only the relevant time slice for each location
  return(cov_val)
}

```


```{r avail method 1: custom buffer size around used points, eval=FALSE}

# Create individually buffered points based on 
sealibuffs <- ssl %>% group_by(deploy_id) %>% st_buffer(dist=ssl$radius*1000) # Convert radius to m
# st_write(sealibuffs, "../Data_Processed/Telemetry/seali_SpeedBuffs.shp")

# Create a list of static covariates 
staticcovars <- raster::stack(dist_land, dist_500m, depth, slope)

# Create a list of all covariates and check resolution 
raslist <- list(depth, dist_land, dist_500m, slope, ship, fish, sst, eke1, eke2, ssh1, ssh2, wind)
rasres <- lapply(raslist, function(x) res(x)/1000)


# Extract available locations from buffered used locations 
# Takes ~ 1.3 hours 

# start <- proc.time()
# # q <- lapply(1:length(sealibuffs$deploy_id),
# #             function(x){custom_extract_avail(sealibuffs[x,], covarstack=staticcovars)})
# avail <- data.frame()
# for(i in 1:length(sealibuffs$deploy_id)){
#   if(i %% 100 == 0){print(i)}
#   q <- custom_extract_avail(sealibuffs[i,], covarstack=staticcovars)
#   avail <- rbind(avail, q)
# }
# 
# # avail <- do.call(rbind, q)
# proc.time()-start
# 
# saveRDS(avail, "../Data_Processed/Telemetry/Available_SpeedBuff_20211003.rds")

# browseURL("https://www.youtube.com/watch?v=K1b8AhIsSYQ")

# Read in previously extracted available locations (created from above code chunk)
avail <- readRDS("../Data_Processed/Telemetry/Available_SpeedBuff_20211003.rds")

# Rename x and y into northing and easting
avail <- avail %>% rename(northing = y, easting= x) %>% 
                   st_as_sf(coords=c("easting", "northing"), remove=F) %>%
                   mutate(used=factor(0))
st_crs(avail) <- st_crs(ssl)

# Extract static covariates at used locations
ssl <- cbind(ssl, raster::extract(staticcovars, ssl))

# Combine available data with used data 
ssl1 <- bind_rows(ssl, avail)

# Extract dynamic weekly covariate values at used and available locations 
# Extract covariate data at used locations 
ssl1$sst <- extract_covar_var_time_custom(xy= st_coordinates(ssl1), t = ssl1$date, covariates=sst)
ssl1$wind <- extract_covar_var_time_custom(xy= st_coordinates(ssl1), t = ssl1$date, covariates=wind)
ssl1$ship <- extract_covar_var_time_custom(xy= st_coordinates(ssl1), t = ssl1$date, covariates=ship)
ssl1$fish <- extract_covar_var_time_custom(xy= st_coordinates(ssl1), t = ssl1$date, covariates=fish)
ssl11 <- ssl1 %>% filter(!date > as.POSIXct("2020-06-01", format="%Y-%m-%d")) %>% mutate(
  ssh = extract_covar_var_time_custom(xy= st_coordinates(.), t = .data$date, covariates=ssh1),
  eke = extract_covar_var_time_custom(xy= st_coordinates(.), t = .data$date, covariates=eke1)
)
ssl12 <- ssl1 %>% filter(date > as.POSIXct("2020-06-01", format="%Y-%m-%d")) %>% mutate(
  ssh = extract_covar_var_time_custom(xy= st_coordinates(.), t = .data$date, covariates=ssh2),
  eke = extract_covar_var_time_custom(xy= st_coordinates(.), t = .data$date, covariates=eke2)
)
ssl1 <- rbind(ssl11, ssl12)

# Drop geometry and standardize column names to lowercase with underscores between words
colnames(ssl1) <- tolower(colnames(ssl1)) 
ssl1 <- ssl1 %>% st_drop_geometry %>% rename(dist_land = distland, dist_500m = dist500m) %>% 
                  dplyr::select(deploy_id, choice_id, used, year, month, weekofyear, lon, lat, 
                                northing, easting, all_of(covar_names)) 

# Convert extracted values to numeric
ssl1[,names(ssl1) != "deploy_id"] <- apply(ssl1[,names(ssl1) != "deploy_id"], 2, function(x){as.numeric(as.character(x))})

# Save output
saveRDS(ssl1, "../Data_Processed/Telemetry/UsedAndAvail_SpeedBuff_20211003.rds")

```

```{r avail method 2: enlarged buffer size around used points, eval=FALSE}

# Create individually buffered points based on 
sealibuffs <- ssl %>% group_by(deploy_id) %>% st_buffer(dist=20000) # Convert radius to m
# st_write(sealibuffs, "../Data_Processed/Telemetry/seali_20kmBuffs.shp")

# Create a list of static covariates 
staticcovars <- raster::stack(dist_land, dist_500m, depth, slope)

# Create a list of all covariates and check resolution 
raslist <- list(depth, dist_land, dist_500m, slope, ship, fish, sst, eke1, eke2, ssh1, ssh2, wind)
rasres <- lapply(raslist, function(x) res(x)/1000)


# Extract available locations from buffered used locations 
# Takes ~ 1.3 hours 

# start <- proc.time()
# # q <- lapply(1:length(sealibuffs$deploy_id),
# #             function(x){custom_extract_avail(sealibuffs[x,], covarstack=staticcovars)})
# avail <- data.frame()
# for(i in 1:length(sealibuffs$deploy_id)){
#   if(i %% 100 == 0){print(i)}
#   q <- custom_extract_avail(sealibuffs[i,], covarstack=staticcovars)
#   avail <- rbind(avail, q)
# }
# 
# # avail <- do.call(rbind, q)
# proc.time()-start
# 
# saveRDS(avail, "../Data_Processed/Telemetry/Available_20kmBuff_20211003.rds")

# browseURL("https://www.youtube.com/watch?v=K1b8AhIsSYQ")

# Read in previously extracted available locations (created from above code chunk)
avail <- readRDS("../Data_Processed/Telemetry/Available_20kmBuff_20211003.rds") %>% mutate(used=factor(used)) # Fixed in code above can remove once rerun

# Rename x and y into northing and easting
avail <- avail %>% rename(northing = y, easting= x) %>% st_as_sf(coords=c("easting", "northing"), remove=F) 
st_crs(avail) <- st_crs(ssl)

# Extract static covariates at used locations
ssl <- cbind(ssl, raster::extract(staticcovars, ssl))

# Combine available data with used data 
ssl2 <- bind_rows(ssl, avail)

# Extract dynamic weekly covariate values at used and available locations 
# Extract covariate data at used locations 
ssl2$sst <- extract_covar_var_time_custom(xy= st_coordinates(ssl2), t = ssl2$date, covariates=sst)
ssl2$wind <- extract_covar_var_time_custom(xy= st_coordinates(ssl2), t = ssl2$date, covariates=wind)
ssl2$ship <- extract_covar_var_time_custom(xy= st_coordinates(ssl2), t = ssl2$date, covariates=ship)
ssl2$fish <- extract_covar_var_time_custom(xy= st_coordinates(ssl2), t = ssl2$date, covariates=fish)
ssl21 <- ssl2 %>% filter(!date > as.POSIXct("2020-06-01", format="%Y-%m-%d")) %>% mutate(
  ssh = extract_covar_var_time_custom(xy= st_coordinates(.), t = .data$date, covariates=ssh1),
  eke = extract_covar_var_time_custom(xy= st_coordinates(.), t = .data$date, covariates=eke1)
)
ssl22 <- ssl2 %>% filter(date > as.POSIXct("2020-06-01", format="%Y-%m-%d")) %>% mutate(
  ssh = extract_covar_var_time_custom(xy= st_coordinates(.), t = .data$date, covariates=ssh2),
  eke = extract_covar_var_time_custom(xy= st_coordinates(.), t = .data$date, covariates=eke2)
)
ssl2 <- rbind(ssl21, ssl22)

# Drop geometry and standardize column names to lowercase with underscores between words
colnames(ssl2) <- tolower(colnames(ssl2)) 
ssl2 <- ssl2 %>% st_drop_geometry %>% rename(dist_land = distland, dist_500m = dist500m) %>% 
                  dplyr::select(deploy_id, choice_id, used, year, month, weekofyear, lon, lat, 
                                northing, easting, all_of(covar_names)) 


# Convert extracted values to numeric
ssl2[,names(ssl2) != "deploy_id"] <- apply(ssl2[,names(ssl2) != "deploy_id"], 2, function(x){as.numeric(as.character(x))})

# Save output
saveRDS(ssl2, "../Data_Processed/Telemetry/UsedAndAvail_20kmBuff_20211003.rds")

```

```{r avail method 3: resample covars to 5 km, eval=FALSE}


# Create individually buffered points based on 
sealibuffs <- ssl %>% group_by(deploy_id) %>% st_buffer(dist=ssl$radius*1000) # Convert radius to m
# st_write(sealibuffs, "../Data_Processed/sealibuffs.shp")

# Create 5km raster template
ras_5km <- crop(fish, study)
res(ras_5km) <- 5000

# NOT SURE WHY THIS ISN'T WORKING.... WHAT'S UP WITH THE FILE CONNECTION? WILL TRY OVER AGAIN FROM BEGINNING
depth_5km <- resample(depth, ras_5km)
dist_land_5km <- resample(dist_land, ras_5km)
dist_500m_5km <- resample(dist_500m, ras_5km)
slope_5km <- resample(slope, ras_5km)
ship_5km <- resample(ship, ras_5km) %>% setZ(getZ(ship))
fish_5km <- resample(fish, ras_5km) %>% setZ(getZ(fish))
sst_5km <- resample(sst, ras_5km) %>% setZ(getZ(sst))
eke1_5km <- resample(eke1, ras_5km) %>% setZ(getZ(eke1))
eke2_5km <- resample(eke2, ras_5km) %>% setZ(getZ(eke2))
ssh1_5km <- resample(ssh1, ras_5km) %>% setZ(getZ(ssh1))
ssh2_5km <- resample(ssh2, ras_5km) %>% setZ(getZ(ssh2))
wind_5km <- resample(wind, ras_5km)  %>% setZ(getZ(wind))


# Create a list of static covariates
staticcovars <- raster::stack(dist_land_5km, dist_500m_5km, depth_5km, slope_5km)

# Create a list of all covariates and check resolution
raslist <- list(depth_5km, dist_land_5km, dist_500m_5km, slope_5km,
                ship_5km, fish_5km, sst_5km, eke1_5km, eke2_5km, ssh1_5km, ssh2_5km, wind_5km)
rasres <- lapply(raslist, function(x) res(x)/1000)

# Extract available locations from buffered used locations
# Takes ~ 1.3 hours
# 
# start <- proc.time()
# # q <- lapply(1:length(sealibuffs$deploy_id),
# #             function(x){custom_extract_avail(sealibuffs[x,], covarstack=staticcovars)})
# avail <- data.frame()
# for(i in 1:length(sealibuffs$deploy_id)){
#   if(i %% 100 == 0){print(i)}
#   q <- custom_extract_avail(sealibuffs[i,], covarstack=staticcovars)
#   avail <- rbind(avail, q)
# }
# 
# # avail <- do.call(rbind, q)
# proc.time()-start
# 
# saveRDS(avail, "../Data_Processed/Telemetry/Available_5kmCell_20211003.rds")

# browseURL("https://www.youtube.com/watch?v=K1b8AhIsSYQ")

# Read in previously extracted available locations (created from above code chunk)
avail <- readRDS("../Data_Processed/Telemetry/Available_5kmCell_20211003.rds")

# Rename x and y into northing and easting
avail <- avail %>% rename(northing = y, easting= x) %>% 
                   st_as_sf(coords=c("easting", "northing"), remove=F) %>%
                   mutate(used=factor(0))
st_crs(avail) <- st_crs(ssl)

# Extract static covariates at used locations
ssl <- cbind(ssl, raster::extract(staticcovars, ssl))

# Combine available data with used data 
ssl3 <- bind_rows(ssl, avail)

# Extract dynamic weekly covariate values at used and available locations 
# Extract covariate data at used locations 
ssl3$sst <- extract_covar_var_time_custom(xy= st_coordinates(ssl3), t = ssl3$date, covariates=sst_5km)
ssl3$wind <- extract_covar_var_time_custom(xy= st_coordinates(ssl3), t = ssl3$date, covariates=wind_5km)
ssl3$ship <- extract_covar_var_time_custom(xy= st_coordinates(ssl3), t = ssl3$date, covariates=ship_5km)
ssl3$fish <- extract_covar_var_time_custom(xy= st_coordinates(ssl3), t = ssl3$date, covariates=fish_5km)
ssl3a <- ssl3 %>% filter(!date > as.POSIXct("2020-06-01", format="%Y-%m-%d")) %>% mutate(
  ssh = extract_covar_var_time_custom(xy= st_coordinates(.), t = .data$date, covariates=ssh1_5km),
  eke = extract_covar_var_time_custom(xy= st_coordinates(.), t = .data$date, covariates=eke1_5km)
)
ssl3b <- ssl3 %>% filter(date > as.POSIXct("2020-06-01", format="%Y-%m-%d")) %>% mutate(
  ssh = extract_covar_var_time_custom(xy= st_coordinates(.), t = .data$date, covariates=ssh2_5km),
  eke = extract_covar_var_time_custom(xy= st_coordinates(.), t = .data$date, covariates=eke2_5km)
)
ssl3 <- rbind(ssl3a, ssl3b)

# Drop geometry and standardize column names to lowercase with underscores between words
colnames(ssl3) <- tolower(colnames(ssl3)) 
ssl3 <- ssl3 %>% st_drop_geometry() %>% rename(dist_land = distland, dist_500m = dist500m) %>% 
                  dplyr::select(deploy_id, choice_id, used, year, month, weekofyear, lon, lat, northing, 
                                easting, all_of(covar_names)) 

# Convert extracted values to numeric
ssl3[,names(ssl3) != "deploy_id"] <- apply(ssl3[,names(ssl3) != "deploy_id"], 2, function(x){as.numeric(as.character(x))})

# Save output
saveRDS(ssl3, "../Data_Processed/Telemetry/UsedAndAvail_5kmCell_20211003.rds")

```
