---
title: "SSLAvailAndCovarExtraction"
author: "Kelly Kapsar"
date: "10/1/2021"
output: html_document
---

```{r load libraries}

library(tidyr)
library(dplyr)
library(sf)
library(raster)
library(ggplot2)
library(scales)
library(ggmap)
library(amt) 
library(lubridate)

```


```{r specify functions}

source("./S0_Functions.R")

# Extract dynamic covariate data at used locations 
### Modified from FROM AMT PACKAGE
# https://github.com/jmsigner/amt/blob/master/R/extract_covariates.R
# Also helpful: https://cran.r-project.org/web/packages/amt/vignettes/p3_rsf.html
# I modified it so that it works with weekly timescale data 
# DOES NOT work with holes in the data set any more 

extract_covar_var_time_custom <- function(
  xy, t, covariates) {

  t_covar <- raster::getZ(covariates)
  wr <- sapply(t, function(x) which(x == t_covar)) # Identify which slice to select
  ev <- raster::extract(covariates, xy) # Extract covariate values for all time slices at all used locations 
  cov_val <- ev[cbind(seq_along(wr), wr)] # select only the relevant time slice for each location
  return(cov_val)
}

```

```{r read in data}

# Set seed
set.seed(1015)

# Projection information for WGS84/UTM Zone 5N (EPSG:32605)
prj <- 32605

# Create study area polygon
coords <- data.frame(lat=c(56, 62, 62, 56, 56), lon=c(-155, -155, -143, -143, -155), id="study")
study <- coords %>% 
         st_as_sf(coords = c("lon", "lat"), crs=4326) %>% 
         group_by(id) %>% 
         summarize(geometry = st_combine(geometry)) %>%  
         st_cast("POLYGON") %>% 
         st_transform(prj)

# Read in clean, non-land ssl used locations
ssl <- readRDS("../Data_Processed/Telemetry/watersealis.rds")
ssl$used <- factor(1)

# Create an ID column that identifies each unique individual/year/season combination
ssl$seasonhr_id <- factor(paste0(ssl$deploy_id,"-", getSeasonYear(ssl$date)))

# st_write(ssl, "../Data_Processed/Telemetry/USedLocs_Clean.shp")

# Read in covariates 
landmask <- raster("../Data_Processed/Landmask_GEBCO.tif")
dist_500m <- raster("../Data_Processed/Dist500m.tif") %>% raster::mask(landmask, maskvalue=1)
depth <- raster("../Data_Processed/Bathymetry.tif") %>% raster::mask(landmask, maskvalue=1)
dist_land <- raster("../Data_Processed/DistLand.tif") %>% raster::mask(landmask, maskvalue=1)
slope <- raster("../Data_Processed/slope.tif") %>% raster::mask(landmask, maskvalue=1)

ship <- readRDS("../Data_Processed/AIS_AllOther_Season.rds") 
fish <- readRDS("../Data_Processed/AIS_Fishing_Season.rds")
sst <- readRDS("../Data_Processed/sst_season.rds")
wind <- readRDS("../Data_Processed/wind_season.rds")

# Create a list of all covariate files  and check resolution 
raslist <- list(depth, dist_land, dist_500m, slope, ship, fish, sst, wind)
rasres <- lapply(raslist, function(x) res(x)/1000)

```


```{r avail method 4: seasonal kde home ranges}

# Remove locations from seasons with <10 locations overall 
pointcounts <- ssl %>% st_drop_geometry() %>% group_by(seasonhr_id) %>% summarize(n=n()) %>% ungroup()
ssl_new <- ssl[-which(ssl$seasonhr_id %in% pointcounts$seasonhr_id[pointcounts$n < 10]),]

# Isolate out variables of interest 
ssl_simple <- ssl_new %>% select(seasonhr_id, date, lon, lat)

# Turn into an amt track
trk <- mk_track(st_drop_geometry(ssl_simple), .x=lon, .y=lat, .t=date, id = seasonhr_id, date=date,
                crs = 4326)
trk.class<-class(trk)

# Calculate time of day based on lat/lon and timestamp
trk <- trk %>% time_of_day()
class(trk) <- trk.class

#' Now, we can transform back to geographic coordinates
trk <- amt::transform_coords(trk, crs_to=32605)

# Summarize sampling rate
summarize_sampling_rate(trk)
summarize_sampling_rate_many(trk, c("id"))

# Create a list of static covariates 
staticcovars <- raster::stack(dist_land, dist_500m, depth, slope)


ssl_hr <- data.frame()
avail_pts <- data.frame()

# Create 5 random non-land points within each weekly MCP for each used point
for(i in 1:length(unique(trk$id))){
  print(i)
  t <- trk[which(trk$id == unique(trk$id)[i]),]
  npts <- pointcounts$n[which(pointcounts$seasonhr_id == unique(trk$id)[i])]*5
  hr_kde <- hr_kde(t, levels=c(0.95))
  pts <- random_points(hr_kde, n = npts) %>% mutate(seasonhr_id = unique(trk$id)[i]) 
  landpts <- st_as_sf(pts, coords=c("x_", "y_"), crs=prj, remove = FALSE) %>% 
             cbind(., raster::extract(staticcovars, .)) %>%
             st_drop_geometry() %>% 
             filter(!is.na(.data$Bathymetry))
  
  while(length(landpts$case_) < npts){
    newpts <- random_points(hr_kde, n = npts-length(landpts$case_)) %>% mutate(seasonhr_id = unique(trk$id)[i])
    newlandpts <- st_as_sf(newpts, coords=c("x_", "y_"), crs=prj,  remove = FALSE) %>% 
             cbind(., raster::extract(staticcovars, .)) %>%
             st_drop_geometry() %>% 
             filter(!is.na(.data$Bathymetry))
    landpts <- rbind(landpts, newlandpts)
  }
  
  
  hr_kde <- hr_isopleths(hr_kde) %>% mutate(seasonhr_id = unique(trk$id)[i])
  
  ssl_hr <- rbind(ssl_hr, hr_kde)
  avail_pts <- rbind(avail_pts, landpts)
}

# Save output polygons 
st_write(ssl_hr, "../Data_Processed/Telemetry/Homerange_KDE_season_20220614.shp")

# Clean up column names in available points 
avail_pts_new <- avail_pts %>% mutate(deploy_id = substr(avail_pts$seasonhr_id, 1, 13), 
                                  season = substr(avail_pts$seasonhr_id, 15, nchar(as.character(avail_pts$seasonhr_id))),
                                  year = substr(avail_pts$seasonhr_id, nchar(as.character(avail_pts$seasonhr_id))-3, nchar(as.character(avail_pts$seasonhr_id))),
                                  used = 0) %>% 
                           rename(northing = y_, easting = x_, dist_land = DistLand, dist_500m = Dist500m) %>%
                           select(-case_)

# Extract raster values and clean up columns for used points 
ssl_newer <- ssl_new %>% 
            select(deploy_id, seasonhr_id, year, date, northing, easting, used) %>% 
            cbind(., raster::extract(staticcovars, .)) %>% 
            mutate(season = getSeasonYear(date)) %>% 
            select(-date) %>% 
            rename(dist_land = DistLand, dist_500m = Dist500m) 

# Merge used with available 
all_pts <- avail_pts_new %>% st_as_sf(., coords=c("easting", "northing"), crs=prj, remove=FALSE) %>% rbind(., ssl_newer)

# Rename to match other naming schemes
ssl4 <- all_pts

# Extract dynamic seasonal covariate values at used and available locations 
ssl4$sst <- extract_covar_var_time_custom(xy= st_coordinates(ssl4), t = ssl4$season, covariates=sst)
ssl4$wind <- extract_covar_var_time_custom(xy= st_coordinates(ssl4), t = ssl4$season, covariates=wind)
ssl4$ship <- extract_covar_var_time_custom(xy= st_coordinates(ssl4), t = ssl4$season, covariates=ship)
ssl4$fish <- extract_covar_var_time_custom(xy= st_coordinates(ssl4), t = ssl4$season, covariates=fish)

# convert column names to lowercase 
colnames(ssl4) <- tolower(colnames(ssl4)) 

# Save output
save(ssl4, file="../Data_Processed/Telemetry/TEMP_seasonal.rda")
```





